- name: mount device according to device uuid
  mount:
    src: UUID={{ item.stdout }}
    path: "{{ outer_item.dest }}"
    fstype: "{{ file_system_type }}"
    state: mounted
  with_items: "{{ result.results }}"
  when: item.item.src == outer_item.src
