---
- name: get public key
  ping:

- name: copy /root/.ssh directory
  copy:
    src=/root/.ssh
    dest=/root/
    directory_mode=0700
    mode=0600

- name: set correct permission for id_rsa.pub and known_hosts
  file: 
    path={{ item }}
    mode=0644
  with_items:
    - /root/.ssh/id_rsa.pub
    - /root/.ssh/known_hosts
