---
#============================ 
devs:
  - dev: /dev/sdb
    prts:
      - start: 0%
        end: 50%
        n: 1
      - start: 50%
        end: 100%
        n: 2
#===========================
file_system_type: xfs
#===========================
mount_info:
  - src: /dev/sdb1
    dest: /CAE
    export_info:
      - nfs_client: 192.168.1.0/16
        export_option: rw,no_root_squash,async,no_subtree_check
  - src: /dev/sdb2
    dest: /CAE2
    export_info:
      - nfs_client: 192.168.1.0/16
        export_option: rw,no_root_squash,async,no_subtree_check

mount_byuuid: yes
#==========================
ib_official_drive: no
