---
- name: mount nfs share in background
  mount: name={{ item.dest }} src={{ item.src }} fstype=nfs state=mounted
  with_items: "{{ mount_info }}"
  async: 1000
  poll: 0
  register: mount_result

- name: 'MOUNT - check on mount nfs share task'
  async_status: jid={{ item.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: 4
  delay: 1
  with_items: "{{ mount_result.results }}"
